// apps/frontend-vue/src/App.vue
<template>
  <main class="page">
    <h1>Vue Frontend</h1>
    <p>{{ message }}</p>
    <button class="btn" @click="onClick">Click me</button>
  </main>
</template>

<script setup lang="ts">
import { ref } from "vue";

const message = ref("Hello from Vue frontend!");

const onClick = () => {
  message.value = "You clicked the Vue button!";
};
</script>

<style>
body {
  margin: 0;
  font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI",
    sans-serif;
}

.page {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  gap: 1rem;
  align-items: center;
  justify-content: center;
  background: #020617;
  color: #e5e7eb;
}

.btn {
  padding: 0.5rem 1rem;
  border-radius: 999px;
  border: none;
  background: #22c55e;
  color: #0f172a;
  font-weight: 600;
  cursor: pointer;
}
</style>

// apps/frontend-react/src/App.tsx
import React, { useState } from "react";

export const App: React.FC = () => {
  const [message, setMessage] = useState("Hello from React frontend!");

  return (
    <main style={styles.page}>
      <h1>React Frontend</h1>
      <p>{message}</p>
      <button
        style={styles.button}
        onClick={() => setMessage("You clicked the button!")}
      >
        Click me
      </button>
    </main>
  );
};

const styles: Record<string, React.CSSProperties> = {
  page: {
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#020617",
    color: "#e5e7eb",
    fontFamily:
      'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif'
  },
  button: {
    padding: "0.5rem 1rem",
    borderRadius: "999px",
    border: "none",
    backgroundColor: "#22c55e",
    color: "#0f172a",
    cursor: "pointer",
    fontWeight: 600
  }
};
